Summary:	Automated music manager for DJ applications
Name:		gjay
Version:	0.3.2
Release:	2
License:	GPLv2+
Group:		Sound
Url:		http://gjay.sourceforge.net/
Source0:	%{name}-%{version}.tar.gz
Patch0:		gjay-0.3.2-sfmt.patch
BuildRequires:	pkgconfig(audacious)
BuildRequires:	pkgconfig(dbus-glib-1)
BuildRequires:	pkgconfig(flac)
BuildRequires:	pkgconfig(gsl)
BuildRequires:	pkgconfig(gtk+-2.0)
BuildRequires:	pkgconfig(vorbis)
Requires:	audacious
Requires:	mp3info
Requires:	mpg321
Requires:	vorbis-tools
# Doesn't get autogenerated as the app doesn't link against it but
# dlopens it: it's not strictly required, so make it a suggests
Suggests:	%{_lib}flac8
Suggests:	%{_lib}vorbis0
Suggests:	%{_lib}vorbisfile3

%description
GJay (Gtk+ DJ) generates playlists across a collection of music (ogg, mp3,
wav) such that each song sounds good following the previous song. It is ideal
for home users who want a non-random way to wander large collections or for
DJs planning a set list. You can generate playlists from within the
application, or run GJay as a standalone command-line utility.

%files
%doc README
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_mandir}/man1/*
%{_datadir}/applications/%{name}.desktop

#----------------------------------------------------------------------------

%prep
%setup -q
%patch0 -p1

%build
%configure2_5x
%make

%install
%makeinstall_std

#menu
mkdir -p %{buildroot}%{_datadir}/applications/
cat << EOF > %{buildroot}%{_datadir}/applications/%{name}.desktop
[Desktop Entry]
Name=GJay
Comment=DJ Collection Manager
Exec=%{_bindir}/%{name}
Icon=sound_section
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;X-MandrivaLinux-CrossDesktop;Audio;Player;
EOF

